spring:
  cloud:
    gateway:
      routes:
        - uri: http://httpbin.org
          id: user-route
          predicates:
            - Path=/user/{method}
            - Method=GET,HEAD,OPTIONS
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiKeyHeaderKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1

